add_cus_dep('nlo', 'nls', 0, 'makenlo2nls');
sub makenlo2nls {
    system("makeindex -s nomencl.ist -o \"$_[0].nls\" -t \"$_[0].nlg\" \"$_[0].nlo\"");
}
push @generated_exts, 'nlo', 'nls', 'nlg', 'glo', 'gls', 'acr', 'acn';
$pdf_mode = 1;
